// demos/ssr-preact/src/server.tsx
import { render as renderToString } from 'preact-render-to-string';
import { App } from './app.js';
import HtmlDocument from './html-document.js';

export const render = () => {
  const document = `<!DOCTYPE html>${renderToString(<HtmlDocument />)}`;
  const html = renderToString(<App />);
  return { document, html };
};

// ssr-demos/ssr-solid/src/server.tsx
import { generateHydrationScript, renderToString } from 'solid-js/web';
import App from './app.js';
import HtmlDocument from './html-document.js';

export const render = () => {
  const document = `<!DOCTYPE html>${renderToString(() => <HtmlDocument />)}`;
  const html = renderToString(App);
  return { document, html, head: generateHydrationScript() };
};
